import { CompanySettings, CostCenter, Rendicion, User, AppNotification, DestinatarioAccount } from './types';

export const INITIAL_COMPANY: CompanySettings = {
  razonSocial: 'CORPORACIÓN ANDINA DE SOLUCIONES Y SERVICIOS S.A.C.',
  ruc: '20608945123',
  direccion: 'Av. Rivera Navarrete 501, Piso 14, San Isidro, Lima - Perú',
  telefono: '(01) 614-8900 / 998-321-456',
  toleranciaCuadre: 2.00,
  logoUrl: '',
  sistemaContableExport: 'CONCAR',
  cuentasOrigenDisponibles: [
    {
      id: 'cta-1',
      banco: 'BCP - Banco de Crédito del Perú',
      tipoCuenta: 'Corriente Soles',
      numeroCuenta: '191-23847291-0-12',
      cci: '002-191-0023847291012-54',
      titular: 'CORPORACIÓN ANDINA S.A.C.',
    },
    {
      id: 'cta-2',
      banco: 'BBVA Continental',
      tipoCuenta: 'Corriente Soles',
      numeroCuenta: '0011-0182-0100492819',
      cci: '011-182-000100492819-32',
      titular: 'CORPORACIÓN ANDINA S.A.C.',
    },
    {
      id: 'cta-3',
      banco: 'Interbank',
      tipoCuenta: 'Corriente Soles',
      numeroCuenta: '200-3001849201',
      cci: '003-200-003001849201-89',
      titular: 'CORPORACIÓN ANDINA S.A.C.',
    },
  ],
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    username: 'admin',
    password: '1234',
    name: 'Ing. Roberto Mendoza',
    email: 'admin@corpandina.com.pe',
    role: 'admin',
    roleLabel: 'Administrador General & Contralor',
    department: 'Dirección y Finanzas',
    dni: '09482716',
    cargo: 'Contralor General & Administrador',
    cuentaBancaria: 'BCP Cta Ahorros 193-94829102-0-15',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-2',
    username: 'jfernandez',
    password: '1234',
    name: 'Lic. Javier Fernández',
    email: 'jfernandez@corpandina.com.pe',
    role: 'gerente',
    roleLabel: 'Gerente de Operaciones (Aprobador)',
    department: 'Operaciones y Campo',
    dni: '10293847',
    cargo: 'Gerente de Operaciones',
    cuentaBancaria: 'BBVA Cta Corriente 0011-0293-0200849201',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-3',
    username: 'mquispe',
    password: '1234',
    name: 'Marcos Quispe Tapia',
    email: 'mquispe@corpandina.com.pe',
    role: 'rendidor',
    roleLabel: 'Supervisor Técnico (Rendidor)',
    department: 'Operaciones y Campo',
    dni: '45892019',
    cargo: 'Supervisor Técnico de Planta y Campo',
    cuentaBancaria: 'BCP Cta Ahorros 194-48291048-0-91',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-4',
    username: 'ccontabilidad',
    password: '1234',
    name: 'CPC Carmen Salinas Prado',
    email: 'contabilidad@corpandina.com.pe',
    role: 'contador',
    roleLabel: 'Auditora Contable & Tesorería',
    department: 'Contabilidad y Finanzas',
    dni: '08291048',
    cargo: 'Auditora Contable y Fiscal Principal',
    cuentaBancaria: 'Interbank Cta Ahorros 200-8492019482',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_COST_CENTERS: CostCenter[] = [
  {
    id: 'cc-1',
    code: 'CC-101',
    name: 'Operaciones y Servicios en Campo',
    department: 'Operaciones',
    budgetLimit: 25000.00,
    spentAmount: 18450.00,
  },
  {
    id: 'cc-2',
    code: 'CC-202',
    name: 'Comercial, Ventas y Licitaciones',
    department: 'Comercial',
    budgetLimit: 15000.00,
    spentAmount: 9800.00,
  },
  {
    id: 'cc-3',
    code: 'CC-303',
    name: 'Tecnología, Sistemas y Redes',
    department: 'Tecnología',
    budgetLimit: 18000.00,
    spentAmount: 11200.00,
  },
  {
    id: 'cc-4',
    code: 'CC-404',
    name: 'Logística, Almacén y Distribución',
    department: 'Logística',
    budgetLimit: 20000.00,
    spentAmount: 16920.00,
  },
  {
    id: 'cc-5',
    code: 'CC-505',
    name: 'Administración y Gestión Corporativa',
    department: 'Administración',
    budgetLimit: 12000.00,
    spentAmount: 7350.00,
  },
];

export const INITIAL_DESTINATARIO_ACCOUNTS: DestinatarioAccount[] = [
  {
    id: 'dest-1',
    nombreDestinatario: 'Marcos Quispe Tapia',
    dniRuc: '45892019',
    banco: 'BCP - Banco de Crédito del Perú',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '194-48291048-0-91',
    cci: '002-194-0048291048091-23',
    alias: 'BCP Ahorros Personal',
  },
  {
    id: 'dest-2',
    nombreDestinatario: 'Marcos Quispe Tapia',
    dniRuc: '45892019',
    banco: 'Interbank',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '200-5829104921',
    cci: '003-200-005829104921-67',
    alias: 'Interbank Ahorros Secundario',
  },
  {
    id: 'dest-3',
    nombreDestinatario: 'Lic. Javier Fernández',
    dniRuc: '10293847',
    banco: 'BBVA Continental',
    tipoCuenta: 'Corriente',
    numeroCuenta: '0011-0293-0200849201',
    cci: '011-293-000200849201-14',
    alias: 'BBVA Cta Operaciones',
  },
  {
    id: 'dest-4',
    nombreDestinatario: 'Ing. Roberto Mendoza',
    dniRuc: '09482716',
    banco: 'BCP - Banco de Crédito del Perú',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '193-94829102-0-15',
    cci: '002-193-0094829102015-88',
    alias: 'BCP Ahorros Haberes',
  },
  {
    id: 'dest-5',
    nombreDestinatario: 'CPC Carmen Salinas Prado',
    dniRuc: '08291048',
    banco: 'Interbank',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '200-8492019482',
    cci: '003-200-008492019482-90',
    alias: 'Interbank Sueldos',
  },
  {
    id: 'dest-6',
    nombreDestinatario: 'Transportes y Logística Rápida S.A.C.',
    dniRuc: '20554891023',
    banco: 'BCP - Banco de Crédito del Perú',
    tipoCuenta: 'Corriente',
    numeroCuenta: '191-38291049-0-45',
    cci: '002-191-0038291049045-71',
    alias: 'BCP Cta Comercial Proveedor',
  },
];

export const INITIAL_RENDICIONES: Rendicion[] = [
  {
    id: 'rend-001',
    codigoRendicion: 'REND-001',
    titulo: 'Comisión de Supervisión de Planta y Obras - Arequipa',
    fechaCreacion: '2025-02-18',
    fechaDesembolso: '2025-02-15',
    fechaRendicion: '2025-02-18',
    colaboradorId: 'usr-3',
    colaboradorNombre: 'Marcos Quispe Tapia',
    responsableRendicion: 'Marcos Quispe Tapia',
    nombreDestinatario: 'Marcos Quispe Tapia',
    cuentaOrigen: 'BCP Cta Cte 191-23847291-0-12 (Empresa)',
    cuentaDestino: 'BCP Cta Ahorros 194-48291048-0-91 (Marcos Quispe Tapia)',
    departamento: 'Operaciones y Campo',
    centroCostosId: 'cc-1',
    tipoDesembolso: 'Transferencia Bancaria',
    numeroTransferencia: 'TRF-90234182',
    numeroCheque: 'CHQ-0045812',
    banco: 'BCP - Banco de Crédito del Perú',
    referenciaRendicion: 'Anticipo viáticos y suministros para supervisión de motores en planta Arequipa',
    montoAsignado: 1450.00,
    estado: 'aprobada',
    aprobadoPor: 'Lic. Javier Fernández',
    fechaAprobacion: '2025-02-19 14:30',
    historialAprobacion: [
      {
        id: 'h-1',
        nivel: 'Nivel 1 - Rendición',
        usuarioNombre: 'Marcos Quispe Tapia',
        usuarioRol: 'Supervisor Técnico',
        fecha: '2025-02-18 10:15',
        accion: 'enviada',
        comentario: 'Rendición ingresada con 5 comprobantes electrónicos y cuadre dentro de la tolerancia de 2 soles.',
      },
      {
        id: 'h-2',
        nivel: 'Nivel 2 - Gerencia de Área',
        usuarioNombre: 'Lic. Javier Fernández',
        usuarioRol: 'Gerente de Operaciones',
        fecha: '2025-02-19 14:30',
        accion: 'aprobada',
        comentario: 'Aprobado desde app móvil. Gastos corresponden a la comisión autorizada.',
      },
    ],
    items: [
      {
        id: 'item-101',
        itemNumber: 1,
        fecha: '2025-02-15',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F001-0028410',
        ruc: '20512839481',
        razonSocial: 'HOTEL EL MIRADOR DE AREQUIPA S.A.C.',
        detalle: 'Alojamiento 2 noches por comisión técnica de inspección',
        clasificacionGasto: 'Alojamiento / Hospedaje',
        centroCostosId: 'cc-1',
        montoTotal: 500.00,
        ocrVerificado: true,
      },
      {
        id: 'item-102',
        itemNumber: 2,
        fecha: '2025-02-16',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F003-0091240',
        ruc: '20100084729',
        razonSocial: 'RESTAURANTES Y SABORES ANDINOS E.I.R.L.',
        detalle: 'Alimentación almuerzo y cena del equipo de trabajo',
        clasificacionGasto: 'Alimentación / Viáticos',
        centroCostosId: 'cc-1',
        montoTotal: 180.00,
        ocrVerificado: true,
      },
      {
        id: 'item-103',
        itemNumber: 3,
        fecha: '2025-02-16',
        tipoDocumento: 'Boleta Electrónica',
        numeroComprobante: 'B014-0012490',
        ruc: '20492817263',
        razonSocial: 'ESTACIÓN DE SERVICIOS SUR S.A.',
        detalle: 'Combustible diésel para camioneta operativa placa V7B-890',
        clasificacionGasto: 'Combustible y Peajes',
        centroCostosId: 'cc-1',
        montoTotal: 300.00,
        ocrVerificado: true,
      },
      {
        id: 'item-104',
        itemNumber: 4,
        fecha: '2025-02-17',
        tipoDocumento: 'Ticket',
        numeroComprobante: 'TCK-0091823',
        ruc: '20381920194',
        razonSocial: 'CONCESIONARIA VIAL DEL SUR PEAJES',
        detalle: 'Peajes ida y retorno tramo Camaná - Arequipa',
        clasificacionGasto: 'Combustible y Peajes',
        centroCostosId: 'cc-1',
        montoTotal: 78.50,
        ocrVerificado: true,
      },
      {
        id: 'item-105',
        itemNumber: 5,
        fecha: '2025-02-17',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F002-0044120',
        ruc: '20601928471',
        razonSocial: 'FERRETERÍA INDUSTRIAL DEL SUR S.A.C.',
        detalle: 'EPP y consumibles de emergencia para prueba de motores',
        clasificacionGasto: 'Materiales y Suministros',
        centroCostosId: 'cc-1',
        montoTotal: 390.00,
        ocrVerificado: true,
      },
    ],
  },
  {
    id: 'rend-002',
    codigoRendicion: 'REND-002',
    titulo: 'Cierre Comercial y Presentación de Licitación - Trujillo',
    fechaCreacion: '2025-02-20',
    fechaDesembolso: '2025-02-18',
    fechaRendicion: '2025-02-20',
    colaboradorId: 'usr-1',
    colaboradorNombre: 'Ing. Roberto Mendoza',
    responsableRendicion: 'Ing. Roberto Mendoza',
    nombreDestinatario: 'Ing. Roberto Mendoza',
    cuentaOrigen: 'BBVA Cta Cte 0011-0182-0100492819 (Empresa)',
    cuentaDestino: 'BCP Cta Ahorros 193-94829102-0-15 (Roberto Mendoza)',
    departamento: 'Comercial y Licitaciones',
    centroCostosId: 'cc-2',
    tipoDesembolso: 'Transferencia Bancaria',
    numeroTransferencia: 'TRF-88129034',
    numeroCheque: 'CHQ-0045813',
    banco: 'BBVA Continental',
    referenciaRendicion: 'Pasajes y viáticos de presentación ejecutiva de propuesta técnica',
    montoAsignado: 2200.00,
    estado: 'liquidada',
    aprobadoPor: 'CPC Carmen Salinas Prado',
    fechaAprobacion: '2025-02-21 16:00',
    historialAprobacion: [
      {
        id: 'h-21',
        nivel: 'Nivel 1 - Rendición',
        usuarioNombre: 'Ing. Roberto Mendoza',
        usuarioRol: 'Gerente General',
        fecha: '2025-02-20 09:00',
        accion: 'enviada',
      },
      {
        id: 'h-22',
        nivel: 'Nivel 3 - Contabilidad',
        usuarioNombre: 'CPC Carmen Salinas Prado',
        usuarioRol: 'Auditora Contable',
        fecha: '2025-02-21 16:00',
        accion: 'liquidada',
        comentario: 'Liquidada con cuadre exacto al 100%. Exportada al sistema contable.',
      },
    ],
    items: [
      {
        id: 'item-201',
        itemNumber: 1,
        fecha: '2025-02-18',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F001-0071239',
        ruc: '20501829401',
        razonSocial: 'AEROLÍNEAS LATAM PERÚ S.A.',
        detalle: 'Pasajes aéreos Lima - Trujillo - Lima con tarifa ejecutiva',
        clasificacionGasto: 'Transporte y Pasajes',
        centroCostosId: 'cc-2',
        montoTotal: 1200.00,
        ocrVerificado: true,
      },
      {
        id: 'item-202',
        itemNumber: 2,
        fecha: '2025-02-19',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F002-0019283',
        ruc: '20481928491',
        razonSocial: 'HOTEL LIBERTADOR TRUJILLO S.A.',
        detalle: 'Hospedaje 1 noche con desayuno ejecutivo',
        clasificacionGasto: 'Alojamiento / Hospedaje',
        centroCostosId: 'cc-2',
        montoTotal: 550.00,
        ocrVerificado: true,
      },
      {
        id: 'item-203',
        itemNumber: 3,
        fecha: '2025-02-19',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F005-0004912',
        ruc: '20601928490',
        razonSocial: 'RESTAURANTE EL MOCHE GOURMET S.A.C.',
        detalle: 'Almuerzo de trabajo con clientes de licitación Minera',
        clasificacionGasto: 'Gastos de Representación',
        centroCostosId: 'cc-2',
        montoTotal: 450.00,
        ocrVerificado: true,
      },
    ],
  },
  {
    id: 'rend-003',
    codigoRendicion: 'REND-003',
    titulo: 'Mantenimiento e Instalación de Servidores Sucursal Piura',
    fechaCreacion: '2025-02-22',
    fechaDesembolso: '2025-02-21',
    fechaRendicion: '2025-02-22',
    colaboradorId: 'usr-3',
    colaboradorNombre: 'Marcos Quispe Tapia',
    responsableRendicion: 'Marcos Quispe Tapia',
    nombreDestinatario: 'Marcos Quispe Tapia',
    cuentaOrigen: 'Interbank Cta Cte 200-3001849201 (Empresa)',
    cuentaDestino: 'BCP Cta Ahorros 194-48291048-0-91 (Marcos Quispe Tapia)',
    departamento: 'Operaciones y Campo',
    centroCostosId: 'cc-3',
    tipoDesembolso: 'Cheque',
    numeroTransferencia: 'TRF-91024855',
    numeroCheque: 'CHQ-0045820',
    banco: 'Interbank',
    referenciaRendicion: 'Cheque de gerencia para compra de patch panels y viáticos en Piura',
    montoAsignado: 1200.00,
    estado: 'pendiente_aprobacion',
    historialAprobacion: [
      {
        id: 'h-31',
        nivel: 'Nivel 1 - Rendición',
        usuarioNombre: 'Marcos Quispe Tapia',
        usuarioRol: 'Supervisor Técnico',
        fecha: '2025-02-22 11:40',
        accion: 'enviada',
        comentario: 'Solicitud lista para aprobación de Gerencia. Saldo restante: S/ 1.80 (cuadre aprobado).',
      },
    ],
    items: [
      {
        id: 'item-301',
        itemNumber: 1,
        fecha: '2025-02-21',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F001-0084920',
        ruc: '20601928410',
        razonSocial: 'CABLES & CONECTIVIDAD INDUSTRIAL PERÚ S.A.C.',
        detalle: 'Bobina de cable Cat6A y patch panels para rack',
        clasificacionGasto: 'Materiales y Suministros',
        centroCostosId: 'cc-3',
        montoTotal: 650.00,
        ocrVerificado: true,
      },
      {
        id: 'item-302',
        itemNumber: 2,
        fecha: '2025-02-21',
        tipoDocumento: 'Recibo por Honorarios',
        numeroComprobante: 'E001-0000142',
        ruc: '10459201941',
        razonSocial: 'CARLOS ALBERTO MEDINA PAREDES',
        detalle: 'Servicio técnico especializado en configuración de fibra óptica',
        clasificacionGasto: 'Servicios de Terceros',
        centroCostosId: 'cc-3',
        montoTotal: 400.00,
        ocrVerificado: true,
      },
      {
        id: 'item-303',
        itemNumber: 3,
        fecha: '2025-02-22',
        tipoDocumento: 'Boleta Electrónica',
        numeroComprobante: 'B002-0048192',
        ruc: '20501829482',
        razonSocial: 'HOTEL & SUITES NORTE PIURA S.A.C.',
        detalle: 'Hospedaje noche técnica Piura',
        clasificacionGasto: 'Alojamiento / Hospedaje',
        centroCostosId: 'cc-3',
        montoTotal: 148.20,
        ocrVerificado: true,
      },
    ],
  },
  {
    id: 'rend-004',
    codigoRendicion: 'REND-004',
    titulo: 'Adquisición de Insumos Logísticos y Distribución Express',
    fechaCreacion: '2025-02-23',
    fechaDesembolso: '2025-02-22',
    fechaRendicion: '2025-02-23',
    colaboradorId: 'usr-3',
    colaboradorNombre: 'Marcos Quispe Tapia',
    responsableRendicion: 'Marcos Quispe Tapia',
    nombreDestinatario: 'Marcos Quispe Tapia',
    cuentaOrigen: 'BCP Cta Cte 191-23847291-0-12 (Empresa)',
    cuentaDestino: 'BCP Cta Ahorros 194-48291048-0-91 (Marcos Quispe Tapia)',
    departamento: 'Logística',
    centroCostosId: 'cc-4',
    tipoDesembolso: 'Transferencia Bancaria',
    numeroTransferencia: 'TRF-93049102',
    numeroCheque: 'CHQ-0045825',
    banco: 'Scotiabank Perú',
    referenciaRendicion: 'Transferencia para fletes y materiales de embalaje urgente',
    montoAsignado: 850.00,
    estado: 'observada',
    observaciones: 'Falta adjuntar el archivo digital legible del comprobante F001-0012948 de embalajes.',
    historialAprobacion: [
      {
        id: 'h-41',
        nivel: 'Nivel 1 - Rendición',
        usuarioNombre: 'Marcos Quispe Tapia',
        usuarioRol: 'Supervisor Técnico',
        fecha: '2025-02-23 08:30',
        accion: 'enviada',
      },
      {
        id: 'h-42',
        nivel: 'Nivel 2 - Gerencia de Área',
        usuarioNombre: 'Lic. Javier Fernández',
        usuarioRol: 'Gerente de Operaciones',
        fecha: '2025-02-23 15:10',
        accion: 'observada',
        comentario: 'Observado: La factura de embalajes no cuenta con el archivo adjunto nítido. Favor subsanar.',
      },
    ],
    items: [
      {
        id: 'item-401',
        itemNumber: 1,
        fecha: '2025-02-22',
        tipoDocumento: 'Factura Electrónica',
        numeroComprobante: 'F001-0012948',
        ruc: '20491829410',
        razonSocial: 'ENVASES Y EMBALAJES NACIONALES S.A.C.',
        detalle: 'Cajas de cartón reforzado y film stretch',
        clasificacionGasto: 'Materiales y Suministros',
        centroCostosId: 'cc-4',
        montoTotal: 520.00,
        ocrVerificado: false,
      },
      {
        id: 'item-402',
        itemNumber: 2,
        fecha: '2025-02-23',
        tipoDocumento: 'Voucher / Transacción',
        numeroComprobante: 'VCH-9812401',
        ruc: '20501928410',
        razonSocial: 'TRANSPORTES Y COURIER RÁPIDO S.A.C.',
        detalle: 'Flete de encomienda urgente hacia sede Chiclayo',
        clasificacionGasto: 'Transporte y Pasajes',
        centroCostosId: 'cc-4',
        montoTotal: 330.00,
        ocrVerificado: true,
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    timestamp: 'Hace 10 minutos',
    titulo: 'Rendición Aprobada por Gerencia',
    mensaje: 'La rendición REND-001 (Arequipa) fue aprobada por Lic. Javier Fernández.',
    tipo: 'aprobacion',
    leido: false,
    rendicionId: 'rend-001',
  },
  {
    id: 'notif-2',
    timestamp: 'Hace 1 hora',
    titulo: 'Nueva Solicitud Pendiente de Aprobación',
    mensaje: 'Marcos Quispe ha enviado la rendición REND-003 para su revisión.',
    tipo: 'rendicion_nueva',
    leido: false,
    rendicionId: 'rend-003',
  },
  {
    id: 'notif-3',
    timestamp: 'Hace 3 horas',
    titulo: 'Rendición Observada',
    mensaje: 'REND-004 fue observada: comprobante digital ilegible.',
    tipo: 'observacion',
    leido: true,
    rendicionId: 'rend-004',
  },
  {
    id: 'notif-4',
    timestamp: 'Ayer',
    titulo: 'Alerta de Límite Presupuestal',
    mensaje: 'El Centro de Costos CC-404 Logística alcanzó el 84.6% de su límite presupuestal.',
    tipo: 'alerta_limite',
    leido: true,
  },
];
